### ISSUE TITLE
Ch 17 is missing

### ISSUE THREAD

**Issue by sixo** [lmassaron/ml4dummies_2ed#1]
Example code shown in your book for chapter 17 seems to be missing in this repository.

**Comment by lmassaron** [comment]
Thank you for noticing me about that. I've just added all the missing files.

**Comment by JohnPaulMueller** [comment]
I'll be creating a blog post about this issue. The original idea was that readers would download the source code from my website at http://www.johnmuellerbooks.com/source-code/ or from the Wiley site at https://www.wiley.com/en-us/Machine+Learning+For+Dummies%2C+2nd+Edition-p-9781119724056. Please check out my blog at http://blog.johnmuellerbooks.com/category/technical/machine-learning-for-dummies-2nd-edition/ for additional content for this book. Thank you for your support!
